name: Docker Image CI

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: artis3n/docker-oraclelinux8-ansible

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: docker/setup-buildx-action@v1.3.0

    - name: Cache Docker layers
      uses: actions/cache@v2.1.6
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Install Goss
      uses: e1himself/goss-installation-action@v1.0.3
      with:
        version: 'v0.3.16'

    - name: Build the Docker image
      uses: docker/build-push-action@v2.4.0
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ${{ env.IMAGE_NAME }}:test
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        build-args: |
          --progress plain
      env:
        DOCKER_BUILDKIT: 1

    - name: Test the Docker image
      run: dgoss run -it --rm --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro ${{ env.IMAGE_NAME }}:test
